import { api } from '../lib/api.js';

export const customerService = {
  getProfile: () => api('/profile'),
  updateProfile: (body) => api('/profile', { method: 'PUT', body }),
  listAddresses: () => api('/addresses'),
  createAddress: (body) => api('/addresses', { method: 'POST', body }),
  getAddress: (id) => api(`/addresses/${id}`),
  updateAddress: (id, body) => api(`/addresses/${id}`, { method: 'PUT', body }),
  deleteAddress: (id) => api(`/addresses/${id}`, { method: 'DELETE' }),
  listCategories: () => api('/categories'),
  listProducts: (query = '') => api(`/products${query}`),
  getProduct: (id) => api(`/products/${id}`),
  getCart: () => api('/cart'),
  addCartItem: (body) => api('/cart/items', { method: 'POST', body }),
  updateCartItem: (productId, body) => api(`/cart/items/${productId}`, { method: 'PUT', body }),
  removeCartItem: (productId) => api(`/cart/items/${productId}`, { method: 'DELETE' }),
  clearCart: () => api('/cart', { method: 'DELETE' }),
  placeOrder: (body) => api('/orders', { method: 'POST', body }),
  listOrders: () => api('/orders'),
  getOrder: (id) => api(`/orders/${id}`),
  initiatePayment: (body) => api('/payments/initiate', { method: 'POST', body }),
  verifyPayment: (body) => api('/payments/verify', { method: 'POST', body }),
  confirmDevPayment: (body) => api('/payments/dev/confirm', { method: 'POST', body }),
  cancelPayment: (body) => api('/payments/cancel', { method: 'POST', body }),
  timeoutPayment: (body) => api('/payments/timeout', { method: 'POST', body }),
  switchToCod: (body) => api('/payments/cod', { method: 'POST', body }),
  getPayment: (orderId) => api(`/payments/order/${orderId}`),
};
